user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # --- Log Format ---
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    # --- Kích hoạt ModSecurity ---
    # Image owasp/modsecurity-crs tự động load module, ta chỉ cần bật nó lên
    modsecurity on;
    # Load file cấu hình mặc định và Rules của OWASP (có sẵn trong image)
    modsecurity_rules_file /etc/modsecurity.d/include.conf;

    # ---Backend (Upstream) ---
    upstream dvwa_backend {
        server dvwa:80;
    }

    upstream juice_backend {
        server juice-shop:3000;
    }

    # --- Server Block: DVWA ---
    server {
        listen 80;
        server_name dvwa.localhost; #http://dvwa.localhost

        location / {
            proxy_pass http://dvwa_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # --- Server Block: JuiceShop ---
    server {
        listen 80;
        server_name juice.localhost; #http://juice.localhost

        location / {
            proxy_pass http://juice_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # --- Server Block mặc định (Chặn truy cập IP trực tiếp hoặc domain lạ) ---
    server {
        listen 80 default_server;
        return 403 "Forbidden: Unknown Host";
    }
}