# ./config/waf/modsecurity.conf
# Cấu hình cơ bản cho ModSecurity Engine

# --- Rule engine initialization ---
# Sử dụng biến môi trường để kiểm soát, nếu không có biến sẽ dùng mặc định là On
# SecRuleEngine On 

# --- Request body handling ---
SecRequestBodyAccess On
SecRequestBodyLimit 134217728 # 128 MB (Cho phép upload file lớn)
SecRequestBodyNoFilesLimit 1048576 # 1 MB (Giới hạn data POST thường)
SecRequestBodyLimitAction Reject 

# Enable JSON and XML parsers
SecRule REQUEST_HEADERS:Content-Type "^(?:application(?:/soap\+|/)|text/)xml" \
"id:200000,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"

SecRule REQUEST_HEADERS:Content-Type "^application/json" \
"id:200001,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=JSON"

# --- Audit log configuration (Dành cho Wazuh) ---
# Chúng ta sử dụng biến môi trường trong docker-compose.yml để override các giá trị này.
# Nếu biến môi trường không có, nó sẽ sử dụng các giá trị này.
# --- Audit Log ---
SecAuditEngine RelevantOnly 
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogFormat JSON
SecAuditLogType Serial
SecAuditLog /var/log/modsec/modsec_audit.log
SecAuditLogParts ABIFHZ

# Nạp file setup mặc định của CRS
Include /opt/owasp-crs/crs-setup.conf.example

# Nạp toàn bộ các luật bảo vệ
Include /opt/owasp-crs/rules/*.conf